name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux
          - os: windows-latest
            label: windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - uses: actions/upload-artifact@v4
      with:
        name: unixtract-${{ matrix.label }}-auto
        path: |
          target/release/unixtract
          target/release/unixtract.exe
          

    
        

