name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Zip linux binary
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd target/release
        zip unixtract-linux-auto.zip unixtract

    - name: Zip windows binary
      if: matrix.os == 'windows-latest'
      run: |
        cd target/release
        7z a unixtract-windows-auto.zip unixtract.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: unixtract-${{ matrix.os }}-auto
        path: target/release/*.zip
        

